// Minimal ABIs — full ABIs generated by Hardhat compile go into artifacts/
// These are typed subsets used by the server and web packages.

export const AUCTION_FACTORY_ABI = [
  "event AuctionCreated(uint256 indexed auctionId, address indexed auction, address indexed seller, address currency, string metadataURI, string imageURI)",
  "function createAuction(address currency, uint256 reservePrice, uint256 minIncrement, uint256 durationSeconds, string metadataURI, string imageURI, address admin) returns (uint256 auctionId, address auction)",
  "function getAuctions(uint256 offset, uint256 limit) view returns (address[])",
  "function nextId() view returns (uint256)",
  "function auctions(uint256) view returns (address)",
] as const;

export const AUCTION_OPEN_ABI = [
  "event Activated(uint256 startTime, uint256 endTime)",
  "event BidPlaced(address indexed bidder, uint256 amount)",
  "event LeaderChanged(address indexed leader, uint256 amount)",
  "event Ended(address indexed winner, uint256 amount)",
  "event Settled(address indexed seller, address indexed winner, uint256 sellerPayout, uint256 fee)",
  "function activate()",
  "function bid(uint256 amount)",
  "function end()",
  "function settle()",
  "function currentState() view returns (uint8)",
  "function state() view returns (uint8)",
  "function startTime() view returns (uint256)",
  "function endTime() view returns (uint256)",
  "function highestBidder() view returns (address)",
  "function highestBid() view returns (uint256)",
  "function seller() view returns (address)",
  "function reservePrice() view returns (uint256)",
  "function minIncrement() view returns (uint256)",
  "function metadataURI() view returns (string)",
  "function imageURI() view returns (string)",
  "function feeBps() view returns (uint256)",
  "function pause()",
  "function unpause()",
  "function setFee(uint256 feeBps, address feeRecipient)",
] as const;
